In [148]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler


In [149]:
data_dict=load_breast_cancer()

In [150]:
data_dict.keys()

['target_names', 'data', 'target', 'DESCR', 'feature_names']

In [151]:
def initialise_dataset():
    data_dict=load_breast_cancer()
    X,Y = data_dict['data'],data_dict['target']
    
    ##scaling dataset
    scaler = MinMaxScaler()
    X = scaler.fit_transform(X)
    Y=Y.reshape(Y.shape[0],1)
    X=X.T
    Y=Y.T
    return X,Y

In [152]:
def initialise_dimensions(X,Y):
    m,n=(X.T).shape
    return m,n

In [153]:
def initialise_weight(f,layer):
    init_epsilon=10**(-4)
    theta=np.random.rand(f,layer)*(2*init_epsilon)-(init_epsilon)
    return theta

In [154]:
def initialise_bias(layer,m):
    return np.ones((layer,m))

In [155]:
def sigmoid_of(Z):
    return 1.0 / (1.0 + np.exp(-Z))

In [156]:
def derivative_of_sigmoid(x):
    return x*(1-x)

In [157]:
def compute_cost(A2,Y):
    Y_pred1=np.multiply(Y,np.log(A2))
    Y_pred0=np.multiply((1-Y),np.log(1-A2))
    Y_pred=Y_pred1+Y_pred0
    ssum=(-1.0/m)*np.sum(Y_pred)
    return ssum

In [158]:
X,Y=initialise_dataset()
m,n=initialise_dimensions(X,Y)
layer1=50
layer2=1

#initailising weight1 and bias1 for hidden layer 1

theta1=initialise_weight(n,layer1)
bias1=initialise_bias(layer1,m)

#initialising weight2 and bias2 for  output layer i.e. layer 2

theta2=initialise_weight(layer1,layer2)
bias2=initialise_bias(layer2,m)

In [159]:
for epoch in range (0,10000):
#forward propagation

    Z1=(np.dot(theta1.T,X))+bias1
    A1=sigmoid_of(Z1)

    Z2=(np.dot(theta2.T,A1))+bias2
    A2=sigmoid_of(Z2)
    
#     y_pred = np.where(A2 > 0.5, 1, 0)
#     print y_pred.shape
#     print Y.shape
#     print y_pred[:7]
#     print Y[:7]
#     print np.sum(y_pred[ : ,1]==Y[ : ,1])
    #now, we have to compute cost function for all the output units. Here the number of output units(k) is 1 

    cost=compute_cost(A2,Y)
    if epoch%1000==0 :
        y_pred = np.where(A2 > 0.5, 1, 0)
        accuracy=(float(np.sum(y_pred.reshape(m)[:]==Y.reshape(m)[:]))/m)*100
    #accuracy = (float(np.sum(y_pred[:,0] == Y[:,0]))/ X.shape[0])* 100
        print ("Cost after iteration %i: %f | accuracy after iteration %i: %f" % (epoch, cost, epoch, accuracy))
    ##back-propagation


    err2=(A2-Y)
    delta_theta2=np.dot(err2,A1.T)
    delta_theta2=delta_theta2.T

    delta_bias2=err2

    ##print delta_theta2.shape,delta_bias2.shape,theta2.shape

    delta1=np.dot(theta2,err2)
    err_1=np.multiply(A1,(1-A1))
    err1=np.multiply(delta1,err_1)
    ##print delta1.shape,err1.shape

    delta_theta1=np.dot(err1,X.T)
    delta_theta1=delta_theta1.T

    delta_bias1=err1

    ##print delta_theta1.shape,delta_bias1.shape,theta1.shape

    theta1=theta1-((0.05/m)*delta_theta1)
    bias1=bias1-((0.05/m)*delta_bias1)
    theta2=theta2-((0.05/m)*delta_theta2)
    bias2=bias2-((0.05/m)*delta_bias2)

Cost after iteration 0: 0.685878 | accuracy after iteration 0: 62.741652
Cost after iteration 1000: 0.639396 | accuracy after iteration 1000: 62.741652
Cost after iteration 2000: 0.619403 | accuracy after iteration 2000: 62.741652
Cost after iteration 3000: 0.599774 | accuracy after iteration 3000: 62.741652
Cost after iteration 4000: 0.564335 | accuracy after iteration 4000: 62.741652
Cost after iteration 5000: 0.298319 | accuracy after iteration 5000: 95.254833
Cost after iteration 6000: 0.156873 | accuracy after iteration 6000: 97.188049
Cost after iteration 7000: 0.112972 | accuracy after iteration 7000: 98.242531
Cost after iteration 8000: 0.089836 | accuracy after iteration 8000: 98.945518
Cost after iteration 9000: 0.074520 | accuracy after iteration 9000: 99.297012


In [141]:
y_pred = np.where(A2 > 0.5, 1, 0)

In [142]:
y_pred.reshape(m)[:60]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1])

In [143]:
Y.reshape(m)[:60]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1])

In [145]:
np.sum(y_pred.reshape(m)[:]==Y.reshape(m)[:])

565

In [146]:
m

569

In [126]:
y_pred=y_pred.reshape(m)

In [127]:
Y=Y.reshape(m)

In [128]:
y_pred[:20]==Y[:20]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True], dtype=bool)